# Generated by Django 3.1.2 on 2020-10-26 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
