# Generated by Django 3.1.2 on 2020-10-26 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0004_auto_20201026_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(blank=True, default='', upload_to='notice')),
            ],
        ),
        migrations.DeleteModel(
            name='notice',
        ),
    ]
