# Generated by Django 3.1.2 on 2020-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0005_auto_20201026_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideshow_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(blank=True, default='', max_length=250)),
                ('photo', models.ImageField(blank=True, default='', upload_to='slideshow')),
            ],
        ),
    ]
