# Generated by Django 3.1.2 on 2020-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0008_slideshow_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bba_students_model',
            name='academic_yr',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='bba_students_model',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='bca_students_model',
            name='academic_yr',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='bca_students_model',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='bcom_students_model',
            name='academic_yr',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='bcom_students_model',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='bed_students_model',
            name='academic_yr',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='bed_students_model',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=25),
        ),
    ]
