# Generated by Django 3.1.2 on 2020-12-22 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0009_auto_20201031_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(blank=True, default='', upload_to='events')),
            ],
        ),
    ]
