# Generated by Django 3.1.2 on 2020-12-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0010_events_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='display_alumni_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, default='', upload_to='slideshow')),
            ],
        ),
    ]
