# Generated by Django 3.1.2 on 2020-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0011_display_alumni_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement_companies_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='august', max_length=9)),
                ('stipened', models.CharField(blank=True, max_length=250)),
                ('bond', models.CharField(blank=True, max_length=10)),
                ('rounds', models.CharField(blank=True, max_length=250)),
                ('syllabus', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
