# Generated by Django 3.1.2 on 2020-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0013_auto_20201223_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit_achievements_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=250)),
                ('achievement_name', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='events_model',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notice_model',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
