# Generated by Django 3.1.2 on 2020-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0014_auto_20201224_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_achievements_model',
            name='checked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submit_achievements_model',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='slideshow'),
        ),
    ]
