# Generated by Django 3.1.2 on 2020-12-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0015_auto_20201224_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow_model',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slideshow_model',
            name='title',
        ),
    ]
