# Generated by Django 3.1.2 on 2020-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0016_auto_20201224_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bba_students_model',
            name='rollno',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bca_students_model',
            name='rollno',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bcom_students_model',
            name='rollno',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bed_students_model',
            name='rollno',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='display_alumni_model',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='placement_companies_model',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='placement_companies_model',
            name='rounds',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='placement_companies_model',
            name='stipend',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='placement_companies_model',
            name='syllabus',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='submit_achievements_model',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
