# Generated by Django 3.1.2 on 2020-12-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0018_auto_20201224_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submit_achievements_model',
            new_name='achievements_model',
        ),
    ]
