# Generated by Django 3.1.2 on 2020-12-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0020_auto_20201224_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements_model',
            name='description',
        ),
        migrations.AlterField(
            model_name='achievements_model',
            name='checked',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], default='unknown', max_length=9),
        ),
    ]
