# Generated by Django 3.1.2 on 2020-12-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0021_auto_20201225_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement_companies_model',
            name='bba',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], default='unknown', max_length=7),
        ),
        migrations.AddField(
            model_name='placement_companies_model',
            name='bca',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], default='unknown', max_length=7),
        ),
        migrations.AddField(
            model_name='placement_companies_model',
            name='bcom',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], default='unknown', max_length=7),
        ),
        migrations.AddField(
            model_name='placement_companies_model',
            name='bed',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], default='unknown', max_length=7),
        ),
        migrations.AlterField(
            model_name='achievements_model',
            name='checked',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], default='unknown', max_length=7),
        ),
    ]
