# Generated by Django 3.1.2 on 2021-01-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0022_auto_20201225_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bca_students_model',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=35),
        ),
    ]
