# Generated by Django 3.1.2 on 2021-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0023_auto_20210108_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=35)),
                ('subject', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='bed_students_model',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=40),
        ),
    ]
