# Generated by Django 3.1.2 on 2021-05-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0024_auto_20210529_1739'),
        ('alumni_app', '0024_auto_20210530_1513'),
    ]

    operations = [
    ]
